# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

kind-dependencies:
    - toolchain
    - fetch

transforms:
    - taskgraph.transforms.build:transforms
    - taskgraph.transforms.build_attrs:transforms
    - taskgraph.transforms.build_lints:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    index:
        product: thunderbird
    treeherder:
        symbol: Searchfox(idx)
        kind: build
        tier: 2
    run-on-projects: []
    optimization: null

jobs:
    linux64-searchfox/debug:
        description: "Linux64 Debug Searchfox"
        index:
            job-name: linux64-searchfox-debug
        treeherder:
            platform: linux64/debug
        worker-type: b-linux
        worker:
            max-run-time: 36000
            env:
                PERFHERDER_EXTRA_OPTIONS: searchfox
                RUSTC_BOOTSTRAP: "1"
                MOZSEARCH_PLATFORM: "linux"
        run:
            using: mozharness
            comm-checkout: true
            actions: [build]
            config-paths:
                - comm/mozharness
            config:
                - builds/taskcluster_base_thunderbird.py
                - builds/releng_sub_linux_configs/64_searchfox_and_debug.py
            script: "mozharness/scripts/fx_desktop_build.py"
            tooltool-downloads: public
            keep-artifacts: false
        fetches:
            toolchain:
                - linux64-binutils
                - linux64-cbindgen
                - linux64-clang
                - linux64-dump-syms
                - linux64-libotr
                - linux64-nasm
                - linux64-node
                - linux64-rust

    macosx64-searchfox/debug:
        description: "MacOS X x64 Debug Cross-compile Searchfox"
        index:
            job-name: macosx64-searchfox-debug
        treeherder:
            platform: osx-cross/debug
        worker-type: b-linux
        worker:
            docker-image: {in-tree: debian10-amd64-build}
            max-run-time: 36000
            env:
                TOOLTOOL_MANIFEST: "browser/config/tooltool-manifests/macosx64/cross-releng.manifest"
                PERFHERDER_EXTRA_OPTIONS: searchfox
                RUSTC_BOOTSTRAP: "1"
                MOZSEARCH_PLATFORM: "macosx"
        run:
            using: mozharness
            comm-checkout: true
            actions: [build]
            config-paths:
                - comm/mozharness
            config:
                - builds/taskcluster_base_thunderbird.py
                - builds/releng_base_mac_64_cross_builds.py
            script: "mozharness/scripts/fx_desktop_build.py"
            custom-build-variant-cfg: cross-debug-searchfox
            tooltool-downloads: internal
            keep-artifacts: false
        fetches:
            toolchain:
                - linux64-binutils
                - linux64-cbindgen
                - linux64-cctools-port
                - linux64-clang-macosx-cross
                - linux64-hfsplus
                - linux64-libdmg
                - linux64-llvm-dsymutil
                - linux64-nasm
                - linux64-node
                - linux64-rust-macos
                - macosx64-libotr

    win64-searchfox/debug:
        description: "Win64 Searchfox Debug (clang-cl)"
        index:
            job-name: win64-searchfox-debug
        treeherder:
            platform: windows2012-64/debug
        worker-type: b-linux
        worker:
            docker-image: {in-tree: debian10-amd64-build}
            max-run-time: 36000
            env:
                TOOLTOOL_MANIFEST: "comm/mail/config/tooltool-manifests/win64/releng.manifest"
                PERFHERDER_EXTRA_OPTIONS: searchfox
                RUSTC_BOOTSTRAP: "1"
                MOZSEARCH_PLATFORM: "windows"
        run:
            using: mozharness
            comm-checkout: true
            options: [append-env-variables-from-configs]
            actions: [build]
            config-paths:
                - comm/mozharness
            script: mozharness/scripts/fx_desktop_build.py
            config:
                - builds/taskcluster_base_thunderbird.py
                - builds/releng_base_linux_64_builds.py
                - builds/taskcluster_sub_win64/searchfox_debug.py
            tooltool-downloads: internal
            extra-config:
                mozconfig_platform: win64
                env:
                    LD_PRELOAD: "/builds/worker/fetches/liblowercase/liblowercase.so"
                    LOWERCASE_DIRS: "/builds/worker/checkouts/gecko/vs2017_15.8.4:/builds/worker/checkouts/gecko/mapiheader"
        use-sccache: true
        fetches:
            toolchain:
                - linux64-binutils
                - linux64-cbindgen
                - linux64-clang-win-cross
                - linux64-dump-syms
                - linux64-liblowercase
                - linux64-nasm
                - linux64-node
                - linux64-rust-cross
                - linux64-rust-size
                - linux64-sccache
                - linux64-winchecksec
                - linux64-wine
                - win64-libotr
            fetch:
                - nsis-3.01-win
                - upx-3.95-win
