# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.release_mark_as_started:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    description: mark release as started in Ship-It v1
    worker-type:
        by-project:
            comm-beta: scriptworker-prov-v1/tb-shipit-v1
            comm-esr60: scriptworker-prov-v1/tb-shipit-v1
            default: scriptworker-prov-v1/tb-shipit-dev
    worker:
        implementation: shipit-started
    scopes:
        by-project:
            comm-beta:
                - project:comm:thunderbird:releng:ship-it:server:production
                - project:comm:thunderbird:releng:ship-it:action:mark-as-started
            comm-esr60:
                - project:comm:thunderbird:releng:ship-it:server:production
                - project:comm:thunderbird:releng:ship-it:action:mark-as-started
            default:
                - project:comm:thunderbird:releng:ship-it:server:staging
                - project:comm:thunderbird:releng:ship-it:action:mark-as-started
    run-on-projects: []
    shipping-phase: promote
    locales-file: comm/mail/locales/l10n-changesets.json

jobs:
    thunderbird:
        name: release-thunderbird_mark_as_started
        shipping-product: thunderbird
        treeherder:
            platform: thunderbird-release/opt
            symbol: Rel(ShipIt-st)
            tier: 1
            kind: build
