[package]
name = "mozilla-central-workspace-hack"
version = "0.1.0"
license = "MPL-2.0"
description = "Thunderbird extensions to mozilla-central-workspace-hack"

[features]
gkrust = []


[workspace]
members = ['gkrust']

[workspace.dependencies]
uniffi = { version = "0.24.3" }

[patch.crates-io]
mozilla-central-workspace-hack = { path = "." }
cmake = { path = "../../build/rust/cmake" }
vcpkg = { path = "../../build/rust/vcpkg" }
mozbuild = { path = "../../build/rust/mozbuild" }
windows-targets = { path = "../../build/rust/windows-targets" }
oslog = { path = "../../build/rust/oslog" }
terminal_size = { path = "../../build/rust/terminal_size" }
bitflags = { path = "../../build/rust/bitflags" }
memmap2 = { path = "../../build/rust/memmap2" }
cfg-if = { path = "../../build/rust/cfg-if" }
serde_with = { path = "../../build/rust/serde_with" }
redox_users = { path = "../../build/rust/redox_users" }
redox_syscall = { path = "../../build/rust/redox_syscall" }
tinyvec = { path = "../../build/rust/tinyvec" }
base64 = { path = "../../build/rust/base64" }
wasi = { path = "../../build/rust/wasi" }
backtrace = { path = "../../build/rust/backtrace" }
bindgen_0_63 = { package = "bindgen", path = "../../build/rust/bindgen-0.63" }
bindgen_0_64 = { package = "bindgen", path = "../../build/rust/bindgen-0.64" }
bindgen = { path = "../../build/rust/bindgen" }
bindgen_0_69 = { package = "bindgen", git = "https://github.com/rust-lang/rust-bindgen", rev = "86f3dbe846020e2ba573d6eb38d1434d0cbcbb40" }
nix = { path = "../../build/rust/nix" }
indexmap = { path = "../../build/rust/indexmap" }
derive_more = { path = "../../build/rust/derive_more" }
autocfg = { path = "../../third_party/rust/autocfg" }
goblin = { path = "../../build/rust/goblin" }
memoffset = { path = "../../build/rust/memoffset" }
js-sys = { path = "../../build/rust/dummy-web/js-sys" }
wasm-bindgen = { path = "../../build/rust/dummy-web/wasm-bindgen" }
web-sys = { path = "../../build/rust/dummy-web/web-sys" }
moz_asserts = { path = "../../mozglue/static/rust/moz_asserts" }
rure = { path = "../../third_party/rust/rure" }
cssparser = { git = "https://github.com/servo/rust-cssparser", rev = "aaa966d9d6ae70c4b8a62bb5e3a14c068bb7dff0" }
cssparser-macros = { git = "https://github.com/servo/rust-cssparser", rev = "aaa966d9d6ae70c4b8a62bb5e3a14c068bb7dff0" }
chardetng = { git = "https://github.com/hsivonen/chardetng", rev = "3484d3e3ebdc8931493aa5df4d7ee9360a90e76b" }
chardetng_c = { git = "https://github.com/hsivonen/chardetng_c", rev = "ed8a4c6f900a90d4dbc1d64b856e61490a1c3570" }
coremidi = { git = "https://github.com/chris-zen/coremidi.git", rev = "fc68464b5445caf111e41f643a2e69ccce0b4f83" }
cose = { git = "https://github.com/franziskuskiefer/cose-rust", rev = "43c22248d136c8b38fe42ea709d08da6355cf04b" }
firefox-on-glean = { path = "../../toolkit/components/glean/api" }
icu_capi = { path = "../../intl/icu_capi" }
icu_segmenter_data = { path = "../../intl/icu_segmenter_data" }
libudev-sys = { path = "../../dom/webauthn/libudev-sys" }
midir = { git = "https://github.com/mozilla/midir.git", rev = "519e651241e867af3391db08f9ae6400bc023e18" }
warp = { git = "https://github.com/seanmonstar/warp", rev = "9d081461ae1167eb321585ce424f4fef6cf0092b" }
malloc_size_of_derive = { path = "../../xpcom/rust/malloc_size_of_derive" }
interrupt-support = { git = "https://github.com/mozilla/application-services", rev = "c82bccfa500813f273f4db0ead64fc73bfa2b34c" }
sql-support = { git = "https://github.com/mozilla/application-services", rev = "c82bccfa500813f273f4db0ead64fc73bfa2b34c" }
suggest = { git = "https://github.com/mozilla/application-services", rev = "c82bccfa500813f273f4db0ead64fc73bfa2b34c" }
sync15 = { git = "https://github.com/mozilla/application-services", rev = "c82bccfa500813f273f4db0ead64fc73bfa2b34c" }
tabs = { git = "https://github.com/mozilla/application-services", rev = "c82bccfa500813f273f4db0ead64fc73bfa2b34c" }
viaduct = { git = "https://github.com/mozilla/application-services", rev = "c82bccfa500813f273f4db0ead64fc73bfa2b34c" }
webext-storage = { git = "https://github.com/mozilla/application-services", rev = "c82bccfa500813f273f4db0ead64fc73bfa2b34c" }
mio = { path = "../../third_party/rust/mio-0.6.23" }

[patch."https://github.com/mozilla/uniffi-rs.git"]
uniffi = "=0.24.3"
uniffi_bindgen = "=0.24.3"
uniffi_build = "=0.24.3"
uniffi_macros = "=0.24.3"
weedle2 = "=4.0.0"
