# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: gecko_taskgraph.loader.transform:loader

kind-dependencies:
    - fetch
    - toolchain

transforms:
    - comm_taskgraph.transforms.repo_update
    - gecko_taskgraph.transforms.release_notifications
    - gecko_taskgraph.transforms.job
    - gecko_taskgraph.transforms.task

jobs:
    tb-rust-vendor:
        name: Thunderbird vendored Rust sync
        description: Check third_party/rust in comm-central matches mozilla-central
        run-on-projects: []  # Only run via cron
        treeherder:
            kind: other
            platform: updatebot/all
            symbol: rust
            tier: 1
        worker-type: b-linux-gcp
        worker:
            docker-image: {in-tree: tb-updatebot}
            max-run-time: 3600
            env:
                REVIEWERS: "#thunderbird-reviewers"
            taskcluster-proxy: true
            artifacts:
                - type: file
                  name: public/hg_diff.patch
                  path: /builds/worker/hg_diff.patch
        ssh-key-secret:
            by-level:
                "3": project/comm/thunderbird/releng/build/level-3/tbirdtry
                default: null
        scopes:
            - secrets:get:project/comm/thunderbird/releng/build/level-{level}/arc-phabricator-token
            - queue:route:notify.matrix-room:!TWztIhgqLawNpRBZTC:mozilla.org.*
        run:
            using: run-task
            comm-checkout: true
            cwd: '/builds/worker'
            command: python3 -m vendor
        notifications:
            subject: 'Thunderbird Rust updatebot failed'
            message: 'Thunderbird Rust updatebot failed'
            status-types:
                - on-failed
                - on-exception
            emails: ["sheriffs@thunderbird.net"]
        fetches:
            toolchain:
                - linux64-rust
                - linux64-cargo-vet
